url: "https://kylase.github.io/CircosAPI"

name: "CircosAPI"
description: "CircosAPI for CIRCOS Data Visualization"

markdown: kramdown
permalink: pretty
highlighter: rouge

analytics: "UA-39189505-1"

circos-version: "0.64"
circos-download-link: "http://circos.ca/distribution/circos-0.64.tgz"
